
services:
  event-gateway:
    build: ./event-gateway
    ports:
      - "8080:8080"
    depends_on:
      - account-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  account-service:
    build: ./account-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
