spring.application.name=event-gateway
spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
server.port=8080
# =========================
# Resilience4j CircuitBreaker
# =========================
resilience4j.circuitbreaker.instances.accountServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.accountServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.accountServiceCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.accountServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountServiceCB.permittedNumberOfCallsInHalfOpenState=3

# =========================
# Resilience4j Retry
# =========================
resilience4j.retry.instances.accountServiceRetry.maxAttempts=3
resilience4j.retry.instances.accountServiceRetry.waitDuration=2s

